### ISSUE TITLE
linear motion while rotating

### ISSUE THREAD

**Issue by jocacace** [husky/husky#105] opened 2019-02-06 11:29 UTC
Hi guys,

I am addressing a problem controlling the husky robot in the gazebo simulator.
I just spawn a husky robot in an empty gazebo world. I am trying to rotate on the place ( I suppose that I am able to do with this platform since it has a differential traction ). For this reason, I just published a geometry_msgs::Twist message filling the .angular.z field with a fixed velocity (let's say 0.3 rad/s).
Sadly, what's happen is that the robot start to glide in the lateral directions. After 3 complete rotation on the place the robot is far of 1, 1.5 meters from the starting position... 

Is this a common behaviour of this platform for this kind of motion??

Thank you, 
Cheers.

**Comment by epiception** [comment] 2019-06-06 18:16
I'm having the same problem. Any quick solutions for this? Any changes that could be made in the controller yaml files?

**Comment by paulsebastian97** [comment] 2019-10-07 17:34
Even I phased this problem. Could anyone help?

**Comment by civerachb-cpr** [comment] 2020-06-02 16:30
This looks like it may be a glitch in Gazebo's physics.  Because Husky's wheels are fixed, when the robot turns on the spot they will skip and skid across the ground, which can result in some lateral movement.

**Comment by civerachb-cpr** [comment] 2020-06-03 15:04
As noted in #99, you may also be able to work-around this issue by moving the Husky's centre of inertia backwards slightly.  This seems to counteract the imbalance that the lidar introduces.

**Comment by And1210** [comment] 2020-06-04 15:23
I was able to change the friction on the wheels which seems to make the robot turn more smoothly. A description of what was done can be found here: https://github.com/husky/husky/issues/120#issuecomment-638921486

**Comment by civerachb-cpr** [comment] 2020-06-04 15:37
Closing this issue, as it seems to be a duplicate of #120 (or at least the discussion is largely a duplication).

**Closed as completed by civerachb-cpr** 2020-06-04 15:37 UTC
