### ISSUE TITLE
UR5 Stow Scripts not working

### ISSUE THREAD

**Issue by wxmerkt** [husky/husky#40] opened 2016-12-06 16:20 UTC
Hi @TheDash 
The stow scripts for our UR5s are not working, it waits forever for the server to come up. We are running firmware version ``3.2.18744`` and the same issue has been reported upstream (https://github.com/ThomasTimm/ur_modern_driver/issues/27#issuecomment-220976342).

Have you run the stow script on the robot and do you have any idea why it may be "waiting for server" forever?

For now we are using our own planning and motion execution pipeline to stow the arms to a desired configuration but it would be great to know why it's not working.

Thanks,
Wolfgang

**Comment by UltronDestroyer** [comment] 2016-12-06 16:37
It is possible that the drivers for the arm aren't coming up/crashing. What does your rostopic list say? Can you ping the arms? What happens when manually launching the arm drivers in /etc/ros/indigo/husky-core.d?

**Comment by wxmerkt** [comment] 2016-12-06 16:41
The drivers work definitely because we are commanding the arms via a SimpleActionClient at the same time when the stow scripts dont work (just tried again).

Manually launching the arm drivers makes them conflict with the ones loaded on boot and they restart alternating - causing communication delays. We figured out that the best mode to operate the robot is to turn on the husky, turn on the arms, restart the husky-core service. Then we dont need to manually start the arms.

**Comment by UltronDestroyer** [comment] 2016-12-06 16:54
Is this an issue with ur_modern_driver then? If it's waiting for server it means that the ur_modern_driver isn't publishing the topic its looking for. Server in this case is referencing the simple action server/trajectory server. If it is indeed up, looks like it might be namespacing issue and a topic relay/remapping will be required.

Can you post your rostopic list and rosservice list for the robot?

**Comment by wxmerkt** [comment] 2016-12-06 17:15
Oh yeah, it was a namespacing issue. After changing to the same topic that we use for our working action client, it can now connect to the server and says so but doesn't move:

```bash
$ rosrun husky_control stow_ur5_left
Waiting for ur5_arm server...
Connected to ur5_arm server
```

I added debug printing and it apparently receives a result immediately after sending the goal (i.e. it immediately completes wait_for_result without having moved at all

**Comment by UltronDestroyer** [comment] 2016-12-06 17:22
Is it in stowed position already? Modifying https://github.com/husky/husky/blob/indigo-devel/husky_control/scripts/stow_ur5#L11 can change its stow position

**Comment by wxmerkt** [comment] 2016-12-06 17:33
Nope, I've moved it into a non-stowed position using our planning/execution pipeline. It still didn't move when commanding to stow it.

**Comment by UltronDestroyer** [comment] 2016-12-07 13:30
Could you confirm what command is being run?

should be something like

rosrun husky_control stow_ur5_left

In addition, can it be confirmed that l_arm_controller/follow_joint_trajectory is up when that is called? The code does this:

>   client = actionlib.SimpleActionClient('l_arm_controller/follow_joint_trajectory', FollowJointTrajectoryAction)
> 	print "Waiting for ur5_arm server..."
> 	client.wait_for_server()
> 	print "Connected to ur5_arm server"
> 	move()

move() gets called, but its unclear whether or not its successful from this block. I see you've dug further than this already. If it's returning immediately, we should look into the ur_modern_driver and see if it has changed at all.

**Comment by wxmerkt** [comment] 2016-12-07 13:47
a) command being run is ``rosrun husky_control stow_ur5_left``
b) I had to change the SimpleAction client to "husky_left_ur5/follow_joint_trajectory" which is the one we are successfully using for executing our trajectories. With the "l_arm_controller" it waits forever for the server to come up.
c) It exits the move() method immediately from the "wait_for_result" line (confirmed by adding a print after wait_for_result

**Comment by tonybaltovski** [comment] 2017-05-08 22:15
@wxmerkt @TheDash I am going to close this since it part of the Dual Arm Husky.

**Closed as completed by tonybaltovski** 2017-05-08 22:15 UTC
