### ISSUE TITLE
Improper husky figure formed in gazebo

### ISSUE THREAD

**Issue by abhileshborode** [husky/husky#98] opened 2018-10-08 01:05 UTC
I am using ROS kinetic. I have a package which launches the husky robot in gazebo, however the gazebo figure launched looks like this:

![screenshot from 2018-10-07 19-01-30](https://user-images.githubusercontent.com/33388291/46589160-e194d280-ca63-11e8-9c59-90ec2fb22061.png)

Please let me know if editing any particular urdf files would fix this issue or not ?

**Comment by tonybaltovski** [comment] 2018-10-17 20:27
Duplicate of husky/husky_simulator#39

**Closed as completed by tonybaltovski** 2018-10-17 20:27 UTC
